# Generated by Django 5.2.5 on 2025-09-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DBapp', '0005_address_owner_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.SmallIntegerField()),
                ('invitees', models.ManyToManyField(to='DBapp.owner')),
            ],
        ),
    ]
