# Generated by Django 5.2.5 on 2025-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mom',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
