# Generated by Django 5.2.4 on 2025-09-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='br_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
